services:
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d  # Mount custom MySQL configuration
    networks:
      - todo-net

  golang-backend:
    build: ./golang-backend
    container_name: golang-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - todo-net

  python-backend:
    build: ./python-backend
    container_name: python-backend
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - todo-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - todo-net

  flyway:
    image: flyway/flyway
    entrypoint: [
      "flyway",
      "-url=jdbc:mysql://mysql:3306/todo_db?useSSL=false&allowPublicKeyRetrieval=true",
      "-user=user",
      "-password=password",
      "-baselineOnMigrate=true",
      "-locations=filesystem:/flyway/sql",
      "migrate"
    ]
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - mysql
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge

volumes:
  mysql_data:
