FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port Vite uses
EXPOSE 3000

# Start Vite in development mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]